config/routes.rb
Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  root 'products#index'
  resources :products do
    collection do
      match 'search' =>  'search_products#index', via: [:get, :post]
    end
  end
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
    self.data = [
        {id: 1, name: '送料込み（配送者負担）'}, {id: 2, name: '着払い（購入者負担）'}
    ]
  end

app/models/delivery_way.rb
class DeliveryWay < ActiveHash::Base
    self.data = [
      {id: 1, name: '未定'}, {id: 2, name: 'らくらくメルカリ便'}, {id: 3, name: 'ゆうメール'},
      {id: 4, name: 'レターパック'}, {id: 5, name: '普通郵便（定形、定形外'}, {id: 6, name: 'クロネコヤマト'},
      {id: 7, name: 'ゆうパック'}, {id: 8, name: 'クリックポスト'}, {id: 9, name: 'ゆうパケット'}
    ]
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :product
    mount_uploader :image, ImageUploader

    validates :image, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :photoes
  validates :photoes, presence: true

end

app/models/product.rb
class Product < ApplicationRecord

  include JpPrefecture
  jp_prefecture :prefecture_code

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  enum status:{on_sale: 1, sold: 2}

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_way
  belongs_to_active_hash :state

  belongs_to :category
end

app/models/state.rb
class State < ActiveHash::Base
    self.data = [
        {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'},{id: 3, name: '目立った傷や汚れなし'},
        {id: 4, name: 'やや傷や汚れあり'},{id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
    ]
  end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @categories = @category.children
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.with_attached_photoes
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      @item.photoes.each do |photo|
        # itemに紐づくphotoのidがparams[:item][:remove_ids]の中に含まれていればpurge
        photo.purge if params[:item][:remove_ids]&.include?(photo.id.to_s)
      end
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.with_attached_photoes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, photoes: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :product_find, except: [:index, :new, :create]

    def index
        @products = Product.includes(:category).all.order('created_at DESC')
        @q = Product.ransack(params[:q])
    end

    def show

    end

    def new
        @product = Product.new
        @product.images.build
    end

    def create
        Product.create!(product_params)
    end

    def edit

    end

    def update
        @product.update!(product_params)
    end

    def destroy
        @product.destroy
    end

    private
    def product_params
        params.require(:product).permit(:name, :description, :category_id, :state_id, :delivery_fee_id, :delivery_way_id, :prefecture_code, :address_city, :address_street, :address_building, :delivery_day, :price, images_attributes: [:image, :_destroy, :id])
    end

    def product_find
        @product = Product.find(params[:id])
    end

end

app/controllers/search_products_controller.rb
class SearchProductsController < ApplicationController
  def index
    @q = Product.ransack(params[:q])
    if params[:product]
      products = Product.where(category_id: Category.find(params[:product][:category_id]).subtree)
      .ransack(search_params)
    else
      products = Product.ransack(search_params)
    end
    @search_results = products.result.includes(:category, :images)
  end

  private

  def search_params
    params.require(:q).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  # ransackのsort_urlを使い、ソート用のurlをvalueに持つハッシュを返す。
  # JSでこの値を使ってソート用URLをリクエストする。
  def ransack_sort_urls
    {
      '並び替え': sort_url(@q, :id, default_order: :asc),
      '価格が安い順': sort_url(@q, :price, default_order: :asc),
      '価格が高い順': sort_url(@q, :price, default_order: :desc),
      '出品の古い順': sort_url(@q, :created_at, default_order: :asc),
      '出品の新しい順': sort_url(@q, :created_at, default_order: :desc),
    }
  end
end

app/views/items/_form.html.haml
= form_for @item, local: true, html: { class: 'js_item-form' } do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    .previews
      - if @item.persisted?
        - @item.photoes.each.with_index(1) do |photo,i|
          .js_item-preview{ data: {index: i} }
            = image_tag photo, height: 100, width: 100
            .btn_wrapper
              %label.js_item-edit{for: "file#{i}"} 編集
              %span.js_item-delete{data: {index: i}} 削除
      = f.label :photoes, "ドラッグ＆ドロップ", class: "js_item-label previews__new-label"
    .photo-inputs
      - if @item.persisted?
        - @item.photoes.each.with_index(1) do |photo,i|
          = f.file_field :photoes, name: 'item[photoes][]', class: 'js_item-file', data: {index: i, id: photo.id }, id: "file#{i}"
      = f.file_field :photoes, name: 'item[photoes][]', class: 'js_item-file'
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td
          = image_tag item.photoes.first, width: "100", height: '100'
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name

%ul{style: 'display: flex;'}
  - @item.photoes.each do |photo|
    %li= image_tag photo, width: "100", height: '100'
= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Miniapp2
    = csrf_meta_tags
    = csp_meta_tag
    %script{:crossorigin => "anonymous", :integrity => "sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=", :src => "https://code.jquery.com/jquery-3.4.0.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/products/_form.html.haml
.content
  = form_for @product do |f|
    #image-box
      #previews.previews
        - if @product.persisted?
          - @product.images.each_with_index do |image, i|
            .preview{"data-index" => i}
              = image_tag image.image.url, width: "100", height: '100', data: {index: i}
              = label_tag :image, '編集', for: "product_images_attributes_#{i}_image"
              .delete-btn.js-remove{"data-index" => i} 削除
        = label_tag :image, "ドラッグ＆ドロップ", class: "js-file_label previews__new-label"
      .js-file_input
        = f.fields_for :images do |image|
          .js-file_group
            = image.file_field :image, data:{ index: image.index }, class: 'js-file'
            - if @product.persisted?
              = image.hidden_field :_destroy, class: 'hidden-check', data:{destroy: image.index}
              = image.hidden_field :id
        - if @product.persisted?
          .js-file_group
            = file_field_tag :image, name: "product[images_attributes][#{@product.images.length}][image]", data:{ index: @product.images.length }, class: 'js-file', id: "product_images_attributes_#{@product.images.length}_image"
    %p 商品名
    = f.text_field :name
    %p 商品説明
    = f.text_area :description
    .categories
      %p カテゴリー
      - if @product.persisted?
        = f.collection_select :category_id, Category.roots, :id, :name, {prompt: '---', selected: @product.category.root.id}, class: 'js-category'
        = f.collection_select :category_id, @product.category.root.children, :id, :name, {prompt: '---', selected: @product.category.parent.id}, class: 'js-category'
        = f.collection_select :category_id, @product.category.siblings, :id, :name, {prompt: '---'}, class: 'js-category'
      - else
        = f.collection_select :category_id, Category.roots, :id, :name, {prompt: '---'}, class: 'js-category'

    %p 商品状態
    = f.collection_select :state_id, State.all, :id, :name
    %p 配送料負担
    = f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :name
    %p 配送方法
    = f.collection_select :delivery_way_id, DeliveryWay.all, :id, :name
    %p 配送元 都道府県
    = f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name
    %p 配送までの日数
    = f.text_field :delivery_day
    日
    %p 販売価格
    = f.text_field :price
    円
    \#{f.submit}
  %a.btn{:href => "/"} トップページに戻る

app/views/products/_product.html.haml
.content
  = image_tag product.images.first.image.url
  %p
    商品名:#{product.name}
  %p
    価格：#{product.price}円
  %div
    %div= product.category.root.name
    %div= product.category.parent.name
    %div= product.category.name
  = link_to '編集', edit_product_path(product)
  = link_to '削除', product_path(product), method: :delete
  %hr/

app/views/products/create.html.haml
%div
  出品完了しました
  %a.btn{:href => "/"} トップページに戻る

app/views/products/destroy.html.haml
%div
  出品を削除しました
  %a.btn{:href => "/"} トップページに戻る

app/views/products/edit.html.haml
= render partial: 'form'

app/views/products/index.html.haml
%div
  = search_form_for @q, url: search_products_path do |f|
    = f.label :name_cont, '商品名'
    = f.text_field :name_cont, {}
    = f.submit
%div
  %a.btn{href: new_product_path} Product出品
  %a.btn{href: new_item_path} Item出品
.contents
  = render @products

app/views/products/new.html.haml
= render partial: 'form'

app/views/products/update.html.haml
%div
  商品を編集しました
  %a.btn{:href => "/"} トップページに戻る

app/views/search_products/index.html.haml
ソート
-# products_helper内のransack_sort_urls(自作)を呼び出してセレクトボックスを作る
= select_tag :sort, options_for_select(ransack_sort_urls), class: 'js-sort'
#search-form
  = search_form_for @q, url: search_products_path do |f|
    %div
      = f.label :name_cont, '商品名'
      = f.text_field :name_cont
    .categories
      = label_tag :category_id, 'カテゴリ'
      = collection_select :product, :category_id, Category.roots, :id, :name, {prompt: '---'}, { name: nil, class: 'js-category'}
    %div
      = f.label :price, '価格'
      = f.number_field :price_gteq
      = f.number_field :price_lteq
    %div
      = f.label :status_in, '取引状態'
      = f.collection_check_boxes :status_in, Product.statuses, :last, :first, {}
    = f.submit
.contents
  = render partial: 'products/product', collection: @search_results, as: :product